module.exports = [
  {"name":"36th Street", "url":"http://e.cdn-surfline.com/syndication/embed/v1/player.html?id=4226"},
  {"name":"17th Street", "url":"http://e.cdn-surfline.com/syndication/embed/v1/player.html?id=4871"},
  {"name":"The Wedge", "url":"http://e.cdn-surfline.com/syndication/embed/v1/player.html?id=4232"},
  {"name":"Blackies", "url":"http://e.cdn-surfline.com/syndication/embed/v1/player.html?id=53412"},
  {"name":"Newport Pier", "url":"http://e.cdn-surfline.com/syndication/embed/v1/player.html?id=4227"},
  {"name":"Huntington Beach", "url":"http://e.cdn-surfline.com/syndication/embed/v1/player.html?id=103681"},
  {"name":"56th Street", "url":"http://e.cdn-surfline.com/syndication/embed/v1/player.html?id=43103"},
  {"name":"Goldenwest", "url":"http://e.cdn-surfline.com/syndication/embed/v1/player.html?id=4870"},
  {"name":"Seal Beach Pier", "url":"http://e.cdn-surfline.com/syndication/embed/v1/player.html?id=4217"},
  {"name":"Salt Creek", "url":"http://e.cdn-surfline.com/syndication/embed/v1/player.html?id=4233"},
  {"name":"Doheny", "url":"http://e.cdn-surfline.com/syndication/embed/v1/player.html?id=4848"},
  {"name":"Thalia", "url":"http://e.cdn-surfline.com/syndication/embed/v1/player.html?id=4235"},
  {"name":"San Clemente Pier", "url":"http://e.cdn-surfline.com/syndication/embed/v1/player.html?id=4843"},
  {"name":"Upper Trestles", "url":"http://e.cdn-surfline.com/syndication/embed/v1/player.html?id=4738"},
  {"name":"Lower Trestles", "url":"http://e.cdn-surfline.com/syndication/embed/v1/player.html?id=4740"},
  {"name":"San Onofre", "url":"http://e.cdn-surfline.com/syndication/embed/v1/player.html?id=109918"},
]
